### PR TITLE
fix bugs

### LINKED ISSUE #101: Bug: add-c
I seem to be able to add a contract between a athlete and contract as long as the athlete name exist BUT the sport does not have to match the athlete.

e.g.
`add-c n/LeBron James s/Football o/Nike sd/01012024 ed/01012025 am/50000000` works though I only have 1 athlete which is LeBron James but his sport is basketball

### LINKED ISSUE #102: Suggestion: delete-c's command structure
Maybe command structure for delete-c can follow add-c where the s/SPORT goes right after a/ATHLETE NAME

Update toString() in DeleteContractCommand.java too and consider changing the ordering for the methods to follow the command structure

### LINKED ISSUE #103: Bug: delete-c
equals() method in DeleteContractCommand is wrong, doesn't check for sport or amount

### LINKED ISSUE #104: Suggestion: add-c's MESSAGE_USAGE
Maybe for MESSAGE_USAGE, can use the athlete and organization mentioned in AddAthleteCommand.java and AddOrganizationCommand.java so that user can just copy and paste command to test our our app instead of having to edit the parameters

### LINKED ISSUE #105: Suggestion: delete-c's MESSAGE_USAGE
Maybe for MESSAGE_USAGE, can use the contract mentioned in AddContractCommand.java  so that user can just copy and paste command to test our our app instead of having to edit the parameters

### LINKED ISSUE #106: Suggestion: organization
Add in how parameter n/NAME should not be blank instead of just "Names can only contain letters, spaces, hyphens, and apostrophes." cause technically blank = spaces. cna copy form athlete Name 

And I suppose numbers aren't allowed but organization eg Hello1 as its name can be created 

Maybe cna align the messages to be the same as athletes classes

### LINKED ISSUE #107: Suggestion : error format standardisation
missing Error: in some outputs
`Date must be DDMMYYYY and a real calendar date (e.g., 01012025).`

`Invalid name: Names should only contain alphabetic characters, spaces, hyphens, and apostrophes, and it should not be blank`

`Invalid phone number: Must be exactly 8 digits.`

And can we please standardise the message for similar parameter eg phone number..?

### PR DESCRIPTION
**Pull request by kellytxn**
Fixes #101 
Fixes #102
Fixes #103
Fixes #104
Fixes #105
Fixes #106
Fixes #107

tldr: fixed the bugs i spotted but I DIDN'T FIX THE TESTS

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/organization/DeleteOrganizationCommand.java [hunk 1]
```diff
@@ -28,7 +28,7 @@ public class DeleteOrganizationCommand extends Command {
 
     public static final String MESSAGE_DELETE_ORGANIZATION_SUCCESS = "Deleted Organisation: %1$s";
     public static final String MESSAGE_ORGANIZATION_NOT_FOUND =
-            "Error: No organisation found with name '%1$s'.";
```
Comment (cameronlzy) [inline src/main/java/seedu/address/logic/commands/organization/DeleteOrganizationCommand.java]: Good job standardising the message behaviour

File: src/main/java/seedu/address/model/athlete/Age.java [hunk 2]
```diff
@@ -10,7 +10,7 @@
 public class Age {
 
     public static final String MESSAGE_CONSTRAINTS =
-            "Invalid age: Ages should be a numeric value between 1 and 99 (inclusive)";
+            "Error: Ages should be a numeric value between 1 and 99 (inclusive)";
```
Comment (cameronlzy) [inline src/main/java/seedu/address/model/athlete/Age.java]: Nice standardising!

File: src/test/java/seedu/address/testutil/Assert.java [hunk 3]
```diff
@@ -14,9 +16,12 @@ public class Assert {
      * with our custom {@link #assertThrows(Class, String, Executable)} method.
      * To standardize API calls in this project, users should use this method instead of
      * {@link Assertions#assertThrows(Class, Executable)}.
+     *
+     * @return
      */
-    public static void assertThrows(Class<? extends Throwable> expectedType, Executable executable) {
+    public static CommandException assertThrows(Class<? extends Throwable> expectedType, Executable executable) {
```
Comment (cameronlzy) [inline src/test/java/seedu/address/testutil/Assert.java]: Good job using assertions!
